### ISSUE TITLE
Provider icon for citybik.es required

### ISSUE THREAD

**Issue by carhartl** [allyapp/design#5]
We start using http://citybik.es for bike sharing routes, thus to comply to their ToS http://api.citybik.es/#tos we need to indicate this in the app by including a provider icon. 

Provider icon for nextbike as an example: 

![provider_icon](https://cloud.githubusercontent.com/assets/21918/9246074/494ec7c4-41a9-11e5-83f6-254f38357967.png)

**Comment by carhartl** [comment]
SVGs provided:
http://citybik.es/files/icon.svg

(Banner alternative: http://citybik.es/files/banner.svg)

**Comment by LejlaR** [comment]
Icon created.
You can find it in the provider_icons folder in dropbox, under the name citybike.svg

**Comment by carhartl** [comment]
@LejlaR The given icon is not rendered correctly in the app. Eren tested it in a application and it seems to be an issue with the viewport, @nickally might know more...

**Comment by carhartl** [comment]
![ios simulator screen shot 01 09 2015 16 02 51](https://cloud.githubusercontent.com/assets/21918/9606323/042999b6-50c3-11e5-98da-29785232bb99.png)
